//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SborkaPreflight.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Programming\\Test\\[day]-[month]\\Layouts\\Approved\\")]
        public string pathApproved {
            get {
                return ((string)(this["pathApproved"]));
            }
            set {
                this["pathApproved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Programming\\Test\\[day]-[month]\\Layouts\\New\\")]
        public string pathNew {
            get {
                return ((string)(this["pathNew"]));
            }
            set {
                this["pathNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Programming\\Test\\[day]-[month]\\Layouts\\PDFs\\")]
        public string pathPDFs {
            get {
                return ((string)(this["pathPDFs"]));
            }
            set {
                this["pathPDFs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Programming\\Test\\[day]-[month]\\Layouts\\Problem\\")]
        public string pathProblem {
            get {
                return ((string)(this["pathProblem"]));
            }
            set {
                this["pathProblem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sborka_Press_new")]
        public string PdfPreset {
            get {
                return ((string)(this["PdfPreset"]));
            }
            set {
                this["PdfPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\(((?<customer>\\d{1,5})-(?<order>\\d{7,8}))\\)")]
        public string regexFullNumberInFileName {
            get {
                return ((string)(this["regexFullNumberInFileName"]));
            }
            set {
                this["regexFullNumberInFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\((\\d{1,4}[xXхХ]\\d{1,4})\\)")]
        public string regexSizeInFileName {
            get {
                return ((string)(this["regexSizeInFileName"]));
            }
            set {
                this["regexSizeInFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".zip,.rar,.7z")]
        public string admissibleExtentions {
            get {
                return ((string)(this["admissibleExtentions"]));
            }
            set {
                this["admissibleExtentions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".tif,.tiff,.jpg,.png,.cdr")]
        public string trueExtentions {
            get {
                return ((string)(this["trueExtentions"]));
            }
            set {
                this["trueExtentions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_[TТ](?<printrun>\\d+)_")]
        public string regexPrintrunInFileName {
            get {
                return ((string)(this["regexPrintrunInFileName"]));
            }
            set {
                this["regexPrintrunInFileName"] = value;
            }
        }
    }
}
